### ISSUE TITLE
Cannot find module './providers/google'

### ISSUE THREAD

**Issue by Johannesklint** [wyattdanger/geocoder#22]
When I initialize: var geocoder = require('geocoder');
i get following error:
Cannot find module './providers/google'

**Comment by SuhairZain** [comment]
Has anyone found a solution to this?

**Comment by sertony** [comment]
@SuhairZain I believe that problem is that you want to use geocoder in react-native project. And as I know react-native's **require** does not work with dynamic strings a-la `require("./providers/"+name)` meanwhile everything should work fine when setting a static one: `require("./providers/google")`.
